//! Chronos Deep-Heal: Audit and Self-Correction Domain
//!
//! Created by Joaquín Escalante (https://github.com/joaquinescalante23)

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

/// The result of a Shadow Audit process.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum AuditVerdict {
    Pass,
    Fail {
        error_log: String,
        suggested_fix: String,
        severity: u8, // 1-5
    },
}

/// A formal audit report generated by the Shadow Layer.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuditReport {
    pub id: Uuid,
    pub agent_id: Uuid,
    pub checkpoint_id: Uuid,
    pub verdict: AuditVerdict,
    pub created_at: DateTime<Utc>,
}

impl AuditReport {
    pub fn new(agent_id: Uuid, checkpoint_id: Uuid, verdict: AuditVerdict) -> Self {
        Self {
            id: Uuid::new_v4(),
            agent_id,
            checkpoint_id,
            verdict,
            created_at: Utc::now(),
        }
    }

    pub fn is_success(&self) -> bool {
        matches!(self.verdict, AuditVerdict::Pass)
    }
}

// Created by Joaquín Escalante (https://github.com/joaquinescalante23)
